### ISSUE TITLE
Constraints cause errors

### ISSUE THREAD

**Issue by Warbo** [mikeizbicki/ifcxt#6]
Consider the following, which returns a comparison function if available (the pragmas are probably overkill!):

```
{-# LANGUAGE RankNTypes, FlexibleInstances, FlexibleContexts, KindSignatures, ScopedTypeVariables, TemplateHaskell, ConstraintKinds #-}

import IfCxt
import Data.Typeable

mkIfCxtInstances ''Ord

getLTE :: forall proxy a. (IfCxt (Ord a)) => proxy (Ord a) -> Maybe (a -> a -> Bool)
getLTE _ = ifCxt (Proxy :: Proxy (Ord a))
                 (Just (<=))
                 Nothing
```

This seems to compile fine:

```
$ ghci foo.hs
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Main             ( foo.hs, interpreted )
Ok, modules loaded: Main.
*Main> 
```

If we use it on a direct instance of `Ord`, we get a comparison function:

```
*Main> maybe "Not found" (const "Found") $ getLTE (Proxy :: Proxy Int)
"Found"
```

If we use it on something which is definitely not in `Ord`, we get `Nothing`:

```
*Main> maybe "Not found" (const "Found") $ getLTE (Proxy :: Proxy (Int -> Int))
"Not found"
```

If we use it on something which is in `Ord` via a constraint, like `Ord a => Ord [a]`, we get a comparion function:

```
*Main> maybe "Not found" (const "Found") $ getLTE (Proxy :: Proxy [Int])
"Found"
```

However, if we use it on something which _isn't_ in `Ord`, due to an unsatisfied constraint, we get a runtime error:

```
*Main> maybe "Not found" (const "Found") $ getLTE (Proxy :: Proxy [Int -> Int])

<interactive>:16:37:
    No instance for (Ord (Int -> Int))
      (maybe you haven't applied enough arguments to a function?)
      arising from a use of ‘getLTE’
    In the second argument of ‘($)’, namely
      ‘getLTE (Proxy :: Proxy [Int -> Int])’
    In the expression:
      maybe "Not found" (const "Found")
      $ getLTE (Proxy :: Proxy [Int -> Int])
    In an equation for ‘it’:
        it
          = maybe "Not found" (const "Found")
            $ getLTE (Proxy :: Proxy [Int -> Int])
```

It would be nice if `ifcxt` would be conservative here, only taking the "then" branch if the constraints are definitely satisfied, and taking the "else" branch otherwise.

**Comment by Warbo** [comment]
Digging into this a little, it's actually a static error: `mkIfCxtInstances` is creating `instance (Ord a) => IfCxt (Ord [a])`, which overrides the catch-all instance :(

**Comment by mikeizbicki** [comment]
This is an interesting example I hadn't thought about.  I probably won't have time to make a fix, but I'd definitely accept a pull request fixing it :)

This also reminds me that I should have made a real test suite and used travis ...

**Comment by Warbo** [comment]
IIRC, this is fixed by https://github.com/mikeizbicki/ifcxt/pull/7

**Comment by mikeizbicki** [comment]
Thanks for tidying this up!
